### ISSUE TITLE
Game crashes when attempting to open a bag

### ISSUE THREAD

**Issue by cielospasteles** [MrZarak/MultiBags#2]
It seems to only happen when the backpack is on the back. I notice it also happens when changing controls too?

[crash-2018-12-24_12.41.10-client.txt](https://github.com/MrZarak/MultiBags/files/2709004/crash-2018-12-24_12.41.10-client.txt)
[crash-2018-12-24_12.54.37-client.txt](https://github.com/MrZarak/MultiBags/files/2709005/crash-2018-12-24_12.54.37-client.txt)

**Comment by MrZarak** [comment]
I think, it is because you have limit of keybinds.
